[hooks]
pre-commit = "cargo fmt && git add . && cargo clippy -- -D warnings && cargo test -- --test-threads=1"
pre-push = "cargo test -- --test-threads=1"
post-commit = "echo NICE JOB!!"


[logging]
verbose = true
