[package]
name = "cli_project_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
clap = { version = "4.5.18", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[dev-dependencies]
tempfile = "3.12.0"
